server:
  port: ${SERVER_PORT}
spring:
  application:
    name: "parking-a-lot"
  devtools:
    add-properties: false
#  h2:
#    console:
#      enabled: true
#      path: "/h2"
#  profiles:
#    include: null
#  datasource:
#    url: "jdbc:h2:mem:test"
#    username: "sa"
#    password: "pass"
#    driverClassName: "org.h2.Driver"
  datasource:
    url: "jdbc:postgresql://localhost:5432/parking_a_lot"
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: "org.postgresql.Driver"
  jpa:
    databasePlatform: "org.hibernate.dialect.PostgreSQLDialect"
    hibernate:
      ddl-auto: "create"
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

#JWT Configuration
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}